###
run ./login.http

### SUBSCRIBE_TO_WIDGET_MESSAGES
POST {{STOMP_API_ENDPOINT}}/subscriptions
Content-Type: application/json

{
  "topics": ["testuser.events"]
}

### CLEAR_MESSAGES
DELETE {{STOMP_API_ENDPOINT}}/subscriptions/testuser.events/messages

### CREATE_REEL_WIDGET
POST {{WIDGET_API_ENDPOINT}}/widgets/commands/add
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "type": "reel",
  "sortOrder": 0,
  "name": "Рулетка"
}

> {%
  client.test("Successfully created Reel widget", function () {
    client.assert(response.status === 200, "200 OK");
    client.assert(
      response.body.id !== undefined && response.body.id !== null,
      "widget has id",
    );
  });
  client.global.set("widgetId", response.body.id);
%}


### SET_PRIZES
PATCH {{WIDGET_API_ENDPOINT}}/widgets/{{widgetId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "config": {
    "properties": [
      { "name": "requiredAmount", "value": 100 },
      {
        "name": "titleFont",
        "value": {
          "family": "Roboto",
          "size": 24,
          "color": {
            "gradient": false,
            "gradientType": 0,
            "repeating": false,
            "colors": [{ "color": "#684aff" }],
            "angle": 0
          },
          "outline": { "enabled": false, "width": 0, "color": "#000000" },
          "weight": false,
          "italic": false,
          "underline": false,
          "shadows": [],
          "animation": "none",
          "animationType": "entire",
          "animationSpeed": "slow"
        }
      },
      {
        "name": "widgetBorder",
        "value": {
          "isSame": null,
          "bottom": { "width": 1, "type": "solid", "color": "#000000" },
          "top": { "width": 1, "type": "solid", "color": "#000000" },
          "left": { "width": 1, "type": "solid", "color": "#000000" },
          "right": { "width": 1, "type": "solid", "color": "#000000" }
        }
      },
      {
        "name": "cardBorder",
        "value": {
          "isSame": null,
          "bottom": { "width": 1, "type": "solid", "color": "#000000" },
          "top": { "width": 1, "type": "solid", "color": "#000000" },
          "left": { "width": 1, "type": "solid", "color": "#000000" },
          "right": { "width": 1, "type": "solid", "color": "#000000" }
        }
      },
      {
        "name": "selectionColor",
        "value": {
          "gradient": false,
          "gradientType": 0,
          "repeating": false,
          "colors": [{ "color": "#FFFFFF" }],
          "angle": 0
        }
      },
      { "name": "reelWinningEffect", "value": { "id": "blink" } },
      { "name": "perView", "value": 5 },
      { "name": "speed", "value": 250 },
      { "name": "time", "value": 10 },
      { "name": "optionList", "value": ["Ничего", "Выигрыш", "123"] },
      { "name": "backgroundImage", "value": null }
    ]
  }
}

### MAKE_PAYMENT
PUT {{PAYMENT_API_ENDPOINT}}/payments/commands/create
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "{{$uuid}}",
  "recipientId": "testuser",
  "nickname": "stCarolas",
  "gatewayCredId": "1",
  "message": "autotest reel {{$timestamp}}",
  "amount": {
    "major": 100,
    "minor": 0,
    "currency": "RUB"
  },
  "attachments": [],
  "goal": null,
  "auction": null,
  "actions": []
}

> {%
  async function wait(ms) {
    return new Promise(resolve => {
      setTimeout(resolve, ms);
    });
  }
  wait(3000);
%}

### CHECK_HISTORY_ITEM
POST {{HISTORY_API_ENDPOINT}}/history/get?size=1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "recipientId": "testuser",
  "systems": []
}

> {%
  let json = response.body.content;

  client.test("Info about reel added to history", function() {
    client.assert(json.length == 1, "Has History Item");
    client.assert(json[0].reelResults !== null, "Info about requested reels is Ready");
    client.assert(
      json[0].reelResults.length == 1,
      "Info about requested reels is Ready")
  });
%}

### GET_STOMP_MESSAGES
GET {{STOMP_API_ENDPOINT}}/subscriptions/testuser.events/messages
Content-Type: application/json

### DELETE_REEL_WIDGET
DELETE {{WIDGET_API_ENDPOINT}}/widgets/{{widgetId}} HTTP/1.1
Authorization: Bearer {{token}}

> {%
  client.test("Successfully deleted Reel widget", function () {
    client.assert(response.status === 200, "200 OK");
  });
%}
