###
run ./login.http

### SUBSCRIBE_TO_WIDGET_MESSAGES
POST {{STOMP_API_ENDPOINT}}/subscriptions
Content-Type: application/json

{
  "topics": ["testuser.events"]
}

### CREATE_REEL_WIDGET
POST {{WIDGET_API_ENDPOINT}}/widgets/commands/add
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "type": "reel",
  "sortOrder": 0,
  "name": "Рулетка"
}

> {%
  client.test("Successfully created Reel widget", function () {
    client.assert(response.status === 200, "200 OK");
    client.assert(
      response.body.id !== undefined && response.body.id !== null,
      "widget has id",
    );
  });
  client.global.set("widgetId", response.body.id);
%}

### MAKE_PAYMENT
PUT {{PAYMENT_API_ENDPOINT}}/payments/commands/create
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "{{$uuid}}",
  "recipientId": "testuser",
  "nickname": "stCarolas",
  "gatewayCredId": "1",
  "message": "autotest reel {{$timestamp}}",
  "amount": {
    "major": 100,
    "minor": 0,
    "currency": "RUB"
  },
  "attachments": [],
  "goal": null,
  "auction": null,
  "actions": []
}

> {%
  async function wait(ms) {
    return new Promise(resolve => {
      setTimeout(resolve, ms);
    });
  }
  wait(3000);
%}

### CHECK_HISTORY_ITEM
POST {{HISTORY_API_ENDPOINT}}/history/get?size=1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "recipientId": "testuser",
  "systems": []
}

> {%
  let json = response.body.content;

  client.test("Info about reel added to history", function() {
    client.assert(json.length == 1, "Has History Item");
    client.assert(json[0].reelResults !== null, "Info about requested reels is Ready");
    client.assert(
      json[0].reelResults.length == 1,
      "Info about requested reels is Ready")
  });
%}

### GET_STOMP_MESSAGES
GET {{STOMP_API_ENDPOINT}}/subscriptions/testuser.events/messages
Content-Type: application/json

### DELETE_REEL_WIDGET
DELETE {{WIDGET_API_ENDPOINT}}/widgets/{{widgetId}} HTTP/1.1
Authorization: Bearer {{token}}

> {%
  client.test("Successfully deleted Reel widget", function () {
    client.assert(response.status === 200, "200 OK");
  });
%}
